travis:
  secure:
    BINSTAR_TOKEN: UWSKn/mNHBPcxe1KN6WhiwIg53HSccdq08ozGvIby6yZViXMJUnkjlfiJJaywRa07kIRMXhIszs91hBG3ubkMJusmwJn6XdOr3RDCmcGbj+aqLGjwGM4HSgAh1Yji2WId+AnmWCJqLl/9fHqcQ9+fE9fdEHyHhz9XVxMc6oT5G32ErlZmSbsZgHbsVKgEJQLC/K8oAlRvK9Wf5yvLwfFZ+jolBc1RmlSvaFc9/d3AJjabygaIzynVSM3rPG4hIIT/WxZ0pF7SITv6TJBXsScGaO3y8mrPkSRQBUDWL55V4YCVl3CK/X9PDREkTmGSkq8bcM6Zw01md67hC2yroppY1PSGhjfKOTcmB2xeJEewyne7DyKeg5CNjQYltlwSPM14n2z5MxEUC9eAuR7eeYl/mw1s+qHpYTDeYU7loycqsHPpOPT2HtQusPd+1n/q3xmC4J5ev6tBDYCk9RTEFEcPWHOmreV/Qmv3mK4XiEQb4bsxqrTtSH5j7RL22dj9HRV8E/WXYPCfvuKb4mlPs7E8Rqw+zwgZ4H7vQgMTdq9Ng8+XRqoyJkxTfAlap12wZ2uPG39kLNABMyz3wSITtCZw/RkDSiMVoGWxeTBskV0xgo6ro0rzBWQo2gGrdjVtk46AGAZ8EOQ/x14Nm46BF/ppBzbPTXCL02oI21tiufqz0c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
